{
 "title": "Stakeiteasy - Solana v0.3",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node1", "label": "Node 1", "query": "vah-stakeiteasy-test" },
   { "name": "node2", "label": "Node 2", "query": "sol02-stakeiteasy-testnet" },
   { "name": "node3", "label": "Node 3", "query": "sol03-stakeiteasy-testnet" },
   { "name": "node4", "label": "Node 4", "query": "sol04-stakeiteasy-testnet" },
   { "name": "node5", "label": "Node 5", "query": "apomykanov-testnet" },
   { "name": "node6", "label": "Node 6", "query": "nikita-pusher-testnet" },
   { "name": "node7", "label": "Node 7", "query": "Dim-testnet" },
   { "name": "node8", "label": "Node 8", "query": "AnMay-testnet" },
   { "name": "node9", "label": "Node 9", "query": "igorautsTdS" },
   { "name": "node10", "label": "Node 10", "query": "autss-testnet" },
   { "name": "node11", "label": "Node 11", "query": "autssvetlana-testnet" },
   { "name": "main1", "label": "Main 1", "query": "vah-stakeiteasy-main" },
   { "name": "mainA1", "label": "mainA1", "query": "iautsMB" },
   { "name": "mainA2", "label": "mainA2", "query": "autss-mainnet" }
  ]
 },
 "panels": [
  { "title": "Testnet epoch info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Testnet Progress",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "validators_info",
     "query": "SELECT \"fields_slotIndex\"*100/ \"fields_slotsInEpoch\" FROM \"validators_info\" WHERE (\"host\" =~ /^$node1$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_slotIndex" ], "type": "field" }
      ],
      [
       { "params": [ "fields_slotsInEpoch" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Epoch end (approx)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_epoch_endtime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Epoch number",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "validators_info",
     "query": "SELECT \"fields_epoch\" FROM \"autogen\".\"validators_info\" WHERE (\"host\" =~ /^$node1$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_epoch" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Cluster skip",
     "measurement": "validators_info",
     "query": "SELECT \"fields_cluster_mean_leader_skip_rate\"  * 100 FROM \"autogen\".\"validators_info\" WHERE (\"host\" =~ /^$node1$/) AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "fields_cluster_mean_leader_skip_rate"
        ],
        "type": "field"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    },
    {
     "alias": "Max all. skip",
     "measurement": "validators_info",
     "query": "SELECT \"fields_cluster_mean_leader_skip_rate\"  * 100 + 30 FROM \"autogen\".\"validators_info\" WHERE (\"host\" =~ /^$node1$/) AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "fields_cluster_mean_leader_skip_rate"
        ],
        "type": "field"
       },
       { "params": [ " * 100 + 30" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mainnet Progress",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "validators_info",
     "query": "SELECT \"fields_slotIndex\"*100/ \"fields_slotsInEpoch\" FROM \"validators_info\" WHERE (\"host\" =~ /^$main1$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_slotIndex" ], "type": "field" }
      ],
      [
       { "params": [ "fields_slotsInEpoch" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Epoch end (approx)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_epoch_endtime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$main1$/" }
     ]
    }
   ]
  },
  {
   "title": "Epoch number",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "validators_info",
     "query": "SELECT \"fields_epoch\" FROM \"autogen\".\"validators_info\" WHERE (\"host\" =~ /^$node1$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_epoch" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$main1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Cluster skip",
     "measurement": "validators_info",
     "query": "SELECT \"fields_cluster_mean_leader_skip_rate\"  * 100 FROM \"autogen\".\"validators_info\" WHERE $timeFilter",
     "select": [
      [
       {
        "params": [
         "fields_cluster_mean_leader_skip_rate"
        ],
        "type": "field"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$main1$/" }
     ]
    },
    {
     "alias": "Max all. skip",
     "measurement": "validators_info",
     "query": "SELECT \"fields_cluster_mean_leader_skip_rate\"  * 100 + 30 FROM \"autogen\".\"validators_info\" WHERE $timeFilter",
     "select": [
      [
       {
        "params": [
         "fields_cluster_mean_leader_skip_rate"
        ],
        "type": "field"
       },
       { "params": [ " * 100 + 30" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$main1$/" }
     ]
    }
   ]
  },
  { "title": "MAIN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "$main1",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 4 },
   "options": { "content": "#" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**voting:** your node has caught up and actively voting  \n**delinquent:** your node is far behind cluster. Maybe after restart, network failure, or any other performance problems.",
   "gridPos": { "h": 1, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "validators_info",
     "query": "SELECT \"fields_voting_status\" FROM \"autogen\".\"validators_info\" WHERE (\"host\" =~ /^$main1$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"autogen\".\"validators_info\" WHERE (\"host\" = '$main1') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**All:** count of your leader slost for current epoch  \n**Done:** count of your processed leader slots  \n**Skipped:** slots where no blocks were produced  \n**Skip rate:** % of skipped slots from slots done  \n**Time to next:** time until next leader slot  \npart of this information comes from `solana block-production -u l | grep  <your identity public key>`",
   "gridPos": { "h": 1, "w": 7, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "All",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$main1') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "fields_my_leader_slots_this_epoch"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jal-testnet" }
     ]
    },
    {
     "alias": "Done",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_done\" FROM \"validators_info\" WHERE (\"host\" = '$main1') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_slots_done" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    },
    {
     "alias": "Skipped",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_skipped\" FROM \"validators_info\" WHERE (\"host\" = '$main1') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_skipped_slots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    },
    {
     "alias": "Skip rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"fields_slots_skipped\"  *100/ \"fields_slots_done\") as skip_perc FROM \"autogen\".\"validators_info\" WHERE $timeFilter AND (\"host\" = '$main1')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Next slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"fields_time_until_next_slot\" FROM \"validators_info\" WHERE (\"host\" = '$main1') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Active",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_active_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$main1$/" }
     ]
    },
    {
     "alias": "New",
     "measurement": "validators_info",
     "query": "SELECT (\"fields_activated_stake\" + \"fields_activating_stake\" - \"fields_deactivating_stake\") / 1000000000 FROM \"validators_info\" WHERE (\"host\" =~ /^$main1$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_activating_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$main1$/" }
     ]
    },
    {
     "alias": "Balance",
     "query": "SELECT \"fields_identity_account_balance\" / 1000000000 FROM \"validators_info\" WHERE (\"host\" =~ /^$main1$/) AND $timeFilter"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 1, "x": 22, "y": 4 },
   "targets": [
    {
     "measurement": "validators_info",
     "query": "SELECT \"fields_voting_status\" FROM \"autogen\".\"validators_info\" WHERE (\"host\" = 'vah-stakeiteasy-main') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "vah-stakeiteasy-main" }
     ]
    }
   ]
  },
  {
   "title": "$mainA1",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 5 },
   "options": { "content": "#" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**voting:** your node has caught up and actively voting  \n**delinquent:** your node is far behind cluster. Maybe after restart, network failure, or any other performance problems.",
   "gridPos": { "h": 1, "w": 2, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "validators_info",
     "query": "SELECT \"fields_voting_status\" FROM \"autogen\".\"validators_info\" WHERE (\"host\" =~ /^$mainA1$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"autogen\".\"validators_info\" WHERE (\"host\" = '$mainA1') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**All:** count of your leader slost for current epoch  \n**Done:** count of your processed leader slots  \n**Skipped:** slots where no blocks were produced  \n**Skip rate:** % of skipped slots from slots done  \n**Time to next:** time until next leader slot  \npart of this information comes from `solana block-production -u l | grep  <your identity public key>`",
   "gridPos": { "h": 1, "w": 7, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "All",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$mainA1') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "fields_my_leader_slots_this_epoch"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jal-testnet" }
     ]
    },
    {
     "alias": "Done",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_done\" FROM \"validators_info\" WHERE (\"host\" = '$mainA1') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_slots_done" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    },
    {
     "alias": "Skipped",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_skipped\" FROM \"validators_info\" WHERE (\"host\" = '$mainA1') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_skipped_slots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    },
    {
     "alias": "Skip rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"fields_slots_skipped\"  *100/ \"fields_slots_done\") as skip_perc FROM \"autogen\".\"validators_info\" WHERE $timeFilter AND (\"host\" = '$mainA1')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Next slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"fields_time_until_next_slot\" FROM \"validators_info\" WHERE (\"host\" = '$mainA1') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Active",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_active_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mainA1$/" }
     ]
    },
    {
     "alias": "New",
     "measurement": "validators_info",
     "query": "SELECT (\"fields_activated_stake\" + \"fields_activating_stake\" - \"fields_deactivating_stake\") / 1000000000 FROM \"validators_info\" WHERE (\"host\" =~ /^$mainA1$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_activating_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$main1$/" }
     ]
    },
    {
     "alias": "Balance",
     "measurement": "validators_info",
     "query": "SELECT \"fields_identity_account_balance\" / 1000000000 FROM \"validators_info\" WHERE (\"host\" =~ /^$mainA1$/) AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "fields_identity_account_balance"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mainA1$/" }
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 1, "x": 22, "y": 5 },
   "targets": [
    {
     "measurement": "validators_info",
     "query": "SELECT \"fields_voting_status\" FROM \"autogen\".\"validators_info\" WHERE (\"host\" = 'iautsMB') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "iautsMB" }
     ]
    }
   ]
  },
  {
   "title": "$mainA2",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 6 },
   "options": { "content": "#" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**voting:** your node has caught up and actively voting  \n**delinquent:** your node is far behind cluster. Maybe after restart, network failure, or any other performance problems.",
   "gridPos": { "h": 1, "w": 2, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "validators_info",
     "query": "SELECT \"fields_voting_status\" FROM \"autogen\".\"validators_info\" WHERE (\"host\" =~ /^$mainA2$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"autogen\".\"validators_info\" WHERE (\"host\" = '$mainA1') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**All:** count of your leader slost for current epoch  \n**Done:** count of your processed leader slots  \n**Skipped:** slots where no blocks were produced  \n**Skip rate:** % of skipped slots from slots done  \n**Time to next:** time until next leader slot  \npart of this information comes from `solana block-production -u l | grep  <your identity public key>`",
   "gridPos": { "h": 1, "w": 7, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "All",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$mainA2') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "fields_my_leader_slots_this_epoch"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jal-testnet" }
     ]
    },
    {
     "alias": "Done",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_done\" FROM \"validators_info\" WHERE (\"host\" = '$mainA2') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_slots_done" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    },
    {
     "alias": "Skipped",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_skipped\" FROM \"validators_info\" WHERE (\"host\" = '$mainA2') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_skipped_slots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    },
    {
     "alias": "Skip rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"fields_slots_skipped\"  *100/ \"fields_slots_done\") as skip_perc FROM \"autogen\".\"validators_info\" WHERE $timeFilter AND (\"host\" = '$mainA2')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Next slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"fields_time_until_next_slot\" FROM \"validators_info\" WHERE (\"host\" = '$mainA2') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Active",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_active_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mainA2$/" }
     ]
    },
    {
     "alias": "New",
     "measurement": "validators_info",
     "query": "SELECT (\"fields_activated_stake\" + \"fields_activating_stake\" - \"fields_deactivating_stake\") / 1000000000 FROM \"validators_info\" WHERE (\"host\" =~ /^$mainA2$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_activating_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$main1$/" }
     ]
    },
    {
     "alias": "Balance",
     "measurement": "validators_info",
     "query": "SELECT \"fields_identity_account_balance\" / 1000000000 FROM \"validators_info\" WHERE (\"host\" =~ /^$mainA2$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_activating_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$main1$/" }
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 1, "x": 22, "y": 6 },
   "targets": [
    {
     "measurement": "validators_info",
     "query": "SELECT \"fields_voting_status\" FROM \"autogen\".\"validators_info\" WHERE (\"host\" = 'autss-mainnet') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "iautsMB" }
     ]
    }
   ]
  },
  { "title": "Stakeiteasy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "$node1",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 8 },
   "options": { "content": "#" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**voting:** your node has caught up and actively voting  \n**delinquent:** your node is far behind cluster. Maybe after restart, network failure, or any other performance problems.",
   "gridPos": { "h": 1, "w": 2, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "validators_info",
     "query": "SELECT \"fields_voting_status\" FROM \"autogen\".\"validators_info\" WHERE (\"host\" =~ /^$node1$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"autogen\".\"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**All:** count of your leader slost for current epoch  \n**Done:** count of your processed leader slots  \n**Skipped:** slots where no blocks were produced  \n**Skip rate:** % of skipped slots from slots done  \n**Time to next:** time until next leader slot  \npart of this information comes from `solana block-production -u l | grep  <your identity public key>`",
   "gridPos": { "h": 1, "w": 7, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "All",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "fields_my_leader_slots_this_epoch"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jal-testnet" }
     ]
    },
    {
     "alias": "Done",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_done\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_slots_done" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    },
    {
     "alias": "Skipped",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_skipped\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_skipped_slots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    },
    {
     "alias": "Skip rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"fields_slots_skipped\"  *100/ \"fields_slots_done\") as skip_perc FROM \"autogen\".\"validators_info\" WHERE $timeFilter AND (\"host\" = '$node1')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Next slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"fields_time_until_next_slot\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Active",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_active_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    },
    {
     "alias": "New",
     "measurement": "validators_info",
     "query": "SELECT (\"fields_activated_stake\" + \"fields_activating_stake\" - \"fields_deactivating_stake\") / 1000000000 FROM \"validators_info\" WHERE (\"host\" =~ /^$node1$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_activated_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    },
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_skipped_slots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 1, "x": 20, "y": 8 },
   "targets": [
    {
     "measurement": "validators_info",
     "query": "SELECT \"fields_voting_status\" FROM \"autogen\".\"validators_info\" WHERE (\"host\" = 'vah-stakeiteasy-test') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "vah-stakeiteasy-test" }
     ]
    }
   ]
  },
  {
   "title": "$node2",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 9 },
   "options": { "content": "#" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**voting:** your node has caught up and actively voting  \n**delinquent:** your node is far behind cluster. Maybe after restart, network failure, or any other performance problems.",
   "gridPos": { "h": 1, "w": 2, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node2$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node2') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**All:** count of your leader slost for current epoch  \n**Done:** count of your processed leader slots  \n**Skipped:** slots where no blocks were produced  \n**Skip rate:** % of skipped slots from slots done  \n**Time to next:** time until next leader slot  \npart of this information comes from `solana block-production -u l | grep  <your identity public key>`",
   "gridPos": { "h": 1, "w": 7, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "All",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node2') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "fields_my_leader_slots_this_epoch"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jal-testnet" }
     ]
    },
    {
     "alias": "Done",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_done\" FROM \"validators_info\" WHERE (\"host\" = '$node2') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_slots_done" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node2$/" }
     ]
    },
    {
     "alias": "Skipped",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_skipped\" FROM \"validators_info\" WHERE (\"host\" = '$node2') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_skipped_slots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node2$/" }
     ]
    },
    {
     "alias": "Skip rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"fields_slots_skipped\"  *100/ \"fields_slots_done\") as skip_perc FROM \"autogen\".\"validators_info\" WHERE $timeFilter AND (\"host\" = '$node2')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Next slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"fields_time_until_next_slot\" FROM \"validators_info\" WHERE (\"host\" = '$node2') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Active",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_active_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node2$/" }
     ]
    },
    {
     "alias": "New",
     "measurement": "validators_info",
     "query": "SELECT (\"fields_activated_stake\" + \"fields_activating_stake\" - \"fields_deactivating_stake\") / 1000000000 FROM \"validators_info\" WHERE (\"host\" =~ /^$node2$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_activated_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node2$/" }
     ]
    },
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_skipped_slots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 1, "x": 20, "y": 9 },
   "targets": [
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sol02-stakeiteasy-testnet" }
     ]
    }
   ]
  },
  {
   "title": "$node3",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 10 },
   "options": { "content": "#" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**voting:** your node has caught up and actively voting  \n**delinquent:** your node is far behind cluster. Maybe after restart, network failure, or any other performance problems.",
   "gridPos": { "h": 1, "w": 2, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node3$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node3') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "$node3\n**All:** count of your leader slost for current epoch  \n**Done:** count of your processed leader slots  \n**Skipped:** slots where no blocks were produced  \n**Skip rate:** % of skipped slots from slots done  \n**Time to next:** time until next leader slot  \npart of this information comes from `solana block-production -u l | grep  <your identity public key>`",
   "gridPos": { "h": 1, "w": 7, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "All",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node3') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "fields_my_leader_slots_this_epoch"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jal-testnet" }
     ]
    },
    {
     "alias": "Done",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_done\" FROM \"validators_info\" WHERE (\"host\" = '$node3') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_slots_done" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node3$/" }
     ]
    },
    {
     "alias": "Skipped",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_skipped\" FROM \"validators_info\" WHERE (\"host\" = '$node3') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_skipped_slots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node3$/" }
     ]
    },
    {
     "alias": "Skip rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"fields_slots_skipped\"  *100/ \"fields_slots_done\") as skip_perc FROM \"autogen\".\"validators_info\" WHERE $timeFilter AND (\"host\" = '$node3')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Next slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"fields_time_until_next_slot\" FROM \"validators_info\" WHERE (\"host\" = '$node3') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 4, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Active",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_active_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node3$/" }
     ]
    },
    {
     "alias": "New",
     "measurement": "validators_info",
     "query": "SELECT (\"fields_activated_stake\" + \"fields_activating_stake\" - \"fields_deactivating_stake\") / 1000000000 FROM \"validators_info\" WHERE (\"host\" =~ /^$node3$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_activated_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node3$/" }
     ]
    },
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_skipped_slots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 1, "x": 20, "y": 10 },
   "targets": [
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sol03-stakeiteasy-testnet" }
     ]
    }
   ]
  },
  {
   "title": "$node4",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 11 },
   "options": { "content": "#" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**voting:** your node has caught up and actively voting  \n**delinquent:** your node is far behind cluster. Maybe after restart, network failure, or any other performance problems.",
   "gridPos": { "h": 1, "w": 2, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node4$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node4') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**All:** count of your leader slost for current epoch  \n**Done:** count of your processed leader slots  \n**Skipped:** slots where no blocks were produced  \n**Skip rate:** % of skipped slots from slots done  \n**Time to next:** time until next leader slot  \npart of this information comes from `solana block-production -u l | grep  <your identity public key>`",
   "gridPos": { "h": 1, "w": 7, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "All",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node4') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "fields_my_leader_slots_this_epoch"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jal-testnet" }
     ]
    },
    {
     "alias": "Done",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_done\" FROM \"validators_info\" WHERE (\"host\" = '$node4') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_slots_done" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node4$/" }
     ]
    },
    {
     "alias": "Skipped",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_skipped\" FROM \"validators_info\" WHERE (\"host\" = '$node4') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_skipped_slots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node4$/" }
     ]
    },
    {
     "alias": "Skip rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"fields_slots_skipped\"  *100/ \"fields_slots_done\") as skip_perc FROM \"autogen\".\"validators_info\" WHERE $timeFilter AND (\"host\" = '$node4')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Next slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"fields_time_until_next_slot\" FROM \"validators_info\" WHERE (\"host\" = '$node4') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 4, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Active",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_active_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node4$/" }
     ]
    },
    {
     "alias": "New",
     "measurement": "validators_info",
     "query": "SELECT (\"fields_activated_stake\" + \"fields_activating_stake\" - \"fields_deactivating_stake\") / 1000000000 FROM \"validators_info\" WHERE (\"host\" =~ /^$node4$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_activated_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node4$/" }
     ]
    },
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_skipped_slots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 1, "x": 20, "y": 11 },
   "targets": [
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sol04-stakeiteasy-testnet" }
     ]
    }
   ]
  },
  { "title": "Nikita's team", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "$node5",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 13 },
   "options": { "content": "#" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**voting:** your node has caught up and actively voting  \n**delinquent:** your node is far behind cluster. Maybe after restart, network failure, or any other performance problems.",
   "gridPos": { "h": 1, "w": 2, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node5$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node5') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**All:** count of your leader slost for current epoch  \n**Done:** count of your processed leader slots  \n**Skipped:** slots where no blocks were produced  \n**Skip rate:** % of skipped slots from slots done  \n**Time to next:** time until next leader slot  \npart of this information comes from `solana block-production -u l | grep  <your identity public key>`",
   "gridPos": { "h": 1, "w": 7, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "All",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node5') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "fields_my_leader_slots_this_epoch"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jal-testnet" }
     ]
    },
    {
     "alias": "Done",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_done\" FROM \"validators_info\" WHERE (\"host\" = '$node5') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_slots_done" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node5$/" }
     ]
    },
    {
     "alias": "Skipped",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_skipped\" FROM \"validators_info\" WHERE (\"host\" = '$node5') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_skipped_slots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node5$/" }
     ]
    },
    {
     "alias": "Skip rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"fields_slots_skipped\"  *100/ \"fields_slots_done\") as skip_perc FROM \"autogen\".\"validators_info\" WHERE $timeFilter AND (\"host\" = '$node5')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Next slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"fields_time_until_next_slot\" FROM \"validators_info\" WHERE (\"host\" = '$node5') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 4, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Active",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_active_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node5$/" }
     ]
    },
    {
     "alias": "New",
     "measurement": "validators_info",
     "query": "SELECT (\"fields_activated_stake\" + \"fields_activating_stake\" - \"fields_deactivating_stake\") / 1000000000 FROM \"validators_info\" WHERE (\"host\" =~ /^$node5$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_activated_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node5$/" }
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 1, "x": 20, "y": 13 },
   "targets": [
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "apomykanov-testnet" }
     ]
    }
   ]
  },
  {
   "title": "$node6",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 14 },
   "options": { "content": "#" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**voting:** your node has caught up and actively voting  \n**delinquent:** your node is far behind cluster. Maybe after restart, network failure, or any other performance problems.",
   "gridPos": { "h": 1, "w": 2, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node6$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node6') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**All:** count of your leader slost for current epoch  \n**Done:** count of your processed leader slots  \n**Skipped:** slots where no blocks were produced  \n**Skip rate:** % of skipped slots from slots done  \n**Time to next:** time until next leader slot  \npart of this information comes from `solana block-production -u l | grep  <your identity public key>`",
   "gridPos": { "h": 1, "w": 7, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "All",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node6') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "fields_my_leader_slots_this_epoch"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jal-testnet" }
     ]
    },
    {
     "alias": "Done",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_done\" FROM \"validators_info\" WHERE (\"host\" = '$node6') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_slots_done" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node6$/" }
     ]
    },
    {
     "alias": "Skipped",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_skipped\" FROM \"validators_info\" WHERE (\"host\" = '$node6') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_skipped_slots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node6$/" }
     ]
    },
    {
     "alias": "Skip rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"fields_slots_skipped\"  *100/ \"fields_slots_done\") as skip_perc FROM \"autogen\".\"validators_info\" WHERE $timeFilter AND (\"host\" = '$node6')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Next slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"fields_time_until_next_slot\" FROM \"validators_info\" WHERE (\"host\" = '$node6') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 4, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Active",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_active_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node6$/" }
     ]
    },
    {
     "alias": "New",
     "measurement": "validators_info",
     "query": "SELECT (\"fields_activated_stake\" + \"fields_activating_stake\" - \"fields_deactivating_stake\") / 1000000000 FROM \"validators_info\" WHERE (\"host\" =~ /^$node6$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_activated_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node6$/" }
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 1, "x": 20, "y": 14 },
   "targets": [
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nikita-pusher-testnet" }
     ]
    }
   ]
  },
  {
   "title": "$node7",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 15 },
   "options": { "content": "#" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**voting:** your node has caught up and actively voting  \n**delinquent:** your node is far behind cluster. Maybe after restart, network failure, or any other performance problems.",
   "gridPos": { "h": 1, "w": 2, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node7$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node7') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**All:** count of your leader slost for current epoch  \n**Done:** count of your processed leader slots  \n**Skipped:** slots where no blocks were produced  \n**Skip rate:** % of skipped slots from slots done  \n**Time to next:** time until next leader slot  \npart of this information comes from `solana block-production -u l | grep  <your identity public key>`",
   "gridPos": { "h": 1, "w": 7, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "All",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node7') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "fields_my_leader_slots_this_epoch"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jal-testnet" }
     ]
    },
    {
     "alias": "Done",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_done\" FROM \"validators_info\" WHERE (\"host\" = '$node7') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_slots_done" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node7$/" }
     ]
    },
    {
     "alias": "Skipped",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_skipped\" FROM \"validators_info\" WHERE (\"host\" = '$node7') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_skipped_slots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node7$/" }
     ]
    },
    {
     "alias": "Skip rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"fields_slots_skipped\"  *100/ \"fields_slots_done\") as skip_perc FROM \"autogen\".\"validators_info\" WHERE $timeFilter AND (\"host\" = '$node7')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Next slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"fields_time_until_next_slot\" FROM \"validators_info\" WHERE (\"host\" = '$node7') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 4, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Active",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_active_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node7$/" }
     ]
    },
    {
     "alias": "New",
     "measurement": "validators_info",
     "query": "SELECT (\"fields_activated_stake\" + \"fields_activating_stake\" - \"fields_deactivating_stake\") / 1000000000 FROM \"validators_info\" WHERE (\"host\" =~ /^$node7$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_activated_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node7$/" }
     ]
    },
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_skipped_slots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 1, "x": 20, "y": 15 },
   "targets": [
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Dim-testnet" }
     ]
    }
   ]
  },
  {
   "title": "$node8",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 16 },
   "options": { "content": "#" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**voting:** your node has caught up and actively voting  \n**delinquent:** your node is far behind cluster. Maybe after restart, network failure, or any other performance problems.",
   "gridPos": { "h": 1, "w": 2, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node8$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node8') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**All:** count of your leader slost for current epoch  \n**Done:** count of your processed leader slots  \n**Skipped:** slots where no blocks were produced  \n**Skip rate:** % of skipped slots from slots done  \n**Time to next:** time until next leader slot  \npart of this information comes from `solana block-production -u l | grep  <your identity public key>`",
   "gridPos": { "h": 1, "w": 7, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "All",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node8') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "fields_my_leader_slots_this_epoch"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jal-testnet" }
     ]
    },
    {
     "alias": "Done",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_done\" FROM \"validators_info\" WHERE (\"host\" = '$node8') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_slots_done" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node8$/" }
     ]
    },
    {
     "alias": "Skipped",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_skipped\" FROM \"validators_info\" WHERE (\"host\" = '$node8') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_skipped_slots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node8$/" }
     ]
    },
    {
     "alias": "Skip rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"fields_slots_skipped\"  *100/ \"fields_slots_done\") as skip_perc FROM \"autogen\".\"validators_info\" WHERE $timeFilter AND (\"host\" = '$node8')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Next slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"fields_time_until_next_slot\" FROM \"validators_info\" WHERE (\"host\" = '$node8') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 4, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Active",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_active_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node8$/" }
     ]
    },
    {
     "alias": "New",
     "measurement": "validators_info",
     "query": "SELECT (\"fields_activated_stake\" + \"fields_activating_stake\" - \"fields_deactivating_stake\") / 1000000000 FROM \"validators_info\" WHERE (\"host\" =~ /^$node8$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_activated_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node8$/" }
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 1, "x": 20, "y": 16 },
   "targets": [
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "AnMay-testnet" }
     ]
    }
   ]
  },
  { "title": "AUTS' team", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "$node9",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 18 },
   "options": { "content": "#" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**voting:** your node has caught up and actively voting  \n**delinquent:** your node is far behind cluster. Maybe after restart, network failure, or any other performance problems.",
   "gridPos": { "h": 1, "w": 2, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node9$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node9') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**All:** count of your leader slost for current epoch  \n**Done:** count of your processed leader slots  \n**Skipped:** slots where no blocks were produced  \n**Skip rate:** % of skipped slots from slots done  \n**Time to next:** time until next leader slot  \npart of this information comes from `solana block-production -u l | grep  <your identity public key>`",
   "gridPos": { "h": 1, "w": 7, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "All",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node9') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "fields_my_leader_slots_this_epoch"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jal-testnet" }
     ]
    },
    {
     "alias": "Done",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_done\" FROM \"validators_info\" WHERE (\"host\" = '$node9') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_slots_done" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node4$/" }
     ]
    },
    {
     "alias": "Skipped",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_skipped\" FROM \"validators_info\" WHERE (\"host\" = '$node9') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_skipped_slots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node4$/" }
     ]
    },
    {
     "alias": "Skip rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"fields_slots_skipped\"  *100/ \"fields_slots_done\") as skip_perc FROM \"autogen\".\"validators_info\" WHERE $timeFilter AND (\"host\" = '$node9')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Next slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"fields_time_until_next_slot\" FROM \"validators_info\" WHERE (\"host\" = '$node9') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 4, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Active",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_active_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node9$/" }
     ]
    },
    {
     "alias": "New",
     "measurement": "validators_info",
     "query": "SELECT (\"fields_activated_stake\" + \"fields_activating_stake\" - \"fields_deactivating_stake\") / 1000000000 FROM \"validators_info\" WHERE (\"host\" =~ /^$node9$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_activated_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node9$/" }
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 1, "x": 20, "y": 18 },
   "targets": [
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "igorautsTdS" }
     ]
    }
   ]
  },
  {
   "title": "$node10",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 19 },
   "options": { "content": "#" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**voting:** your node has caught up and actively voting  \n**delinquent:** your node is far behind cluster. Maybe after restart, network failure, or any other performance problems.",
   "gridPos": { "h": 1, "w": 2, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node10$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node10') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**All:** count of your leader slost for current epoch  \n**Done:** count of your processed leader slots  \n**Skipped:** slots where no blocks were produced  \n**Skip rate:** % of skipped slots from slots done  \n**Time to next:** time until next leader slot  \npart of this information comes from `solana block-production -u l | grep  <your identity public key>`",
   "gridPos": { "h": 1, "w": 7, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "All",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node10') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "fields_my_leader_slots_this_epoch"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jal-testnet" }
     ]
    },
    {
     "alias": "Done",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_done\" FROM \"validators_info\" WHERE (\"host\" = '$node10') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_slots_done" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node4$/" }
     ]
    },
    {
     "alias": "Skipped",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_skipped\" FROM \"validators_info\" WHERE (\"host\" = '$node10') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_skipped_slots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node4$/" }
     ]
    },
    {
     "alias": "Skip rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"fields_slots_skipped\"  *100/ \"fields_slots_done\") as skip_perc FROM \"autogen\".\"validators_info\" WHERE $timeFilter AND (\"host\" = '$node10')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Next slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"fields_time_until_next_slot\" FROM \"validators_info\" WHERE (\"host\" = '$node10') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 4, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Active",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_active_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node10$/" }
     ]
    },
    {
     "alias": "New",
     "measurement": "validators_info",
     "query": "SELECT (\"fields_activated_stake\" + \"fields_activating_stake\" - \"fields_deactivating_stake\") / 1000000000 FROM \"validators_info\" WHERE (\"host\" =~ /^$node10$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_activated_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node10$/" }
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 1, "x": 20, "y": 19 },
   "targets": [
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "autss-testnet" }
     ]
    }
   ]
  },
  {
   "title": "$node11",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 20 },
   "options": { "content": "#" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**voting:** your node has caught up and actively voting  \n**delinquent:** your node is far behind cluster. Maybe after restart, network failure, or any other performance problems.",
   "gridPos": { "h": 1, "w": 2, "x": 4, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node9$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "validators_info",
     "query": "SELECT \"solana_version\" FROM \"validators_info\" WHERE (\"host\" = '$node11') AND $timeFilter",
     "select": [
      [
       { "params": [ "solana_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "validator_name", "operator": "=~", "value": "/^$node1$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "**All:** count of your leader slost for current epoch  \n**Done:** count of your processed leader slots  \n**Skipped:** slots where no blocks were produced  \n**Skip rate:** % of skipped slots from slots done  \n**Time to next:** time until next leader slot  \npart of this information comes from `solana block-production -u l | grep  <your identity public key>`",
   "gridPos": { "h": 1, "w": 7, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "All",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node11') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "fields_my_leader_slots_this_epoch"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jal-testnet" }
     ]
    },
    {
     "alias": "Done",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_done\" FROM \"validators_info\" WHERE (\"host\" = '$node11') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_slots_done" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node4$/" }
     ]
    },
    {
     "alias": "Skipped",
     "measurement": "validators_info",
     "query": "SELECT \"fields_slots_skipped\" FROM \"validators_info\" WHERE (\"host\" = '$node11') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_skipped_slots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node4$/" }
     ]
    },
    {
     "alias": "Skip rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"fields_slots_skipped\"  *100/ \"fields_slots_done\") as skip_perc FROM \"autogen\".\"validators_info\" WHERE $timeFilter AND (\"host\" = '$node11')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Next slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"fields_time_until_next_slot\" FROM \"validators_info\" WHERE (\"host\" = '$node11') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 4, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Active",
     "measurement": "validators_info",
     "query": "SELECT \"fields_leader_slots_this_epoch\" FROM \"validators_info\" WHERE (\"host\" = '$node1') AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_active_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node11$/" }
     ]
    },
    {
     "alias": "New",
     "measurement": "validators_info",
     "query": "SELECT (\"fields_activated_stake\" + \"fields_activating_stake\" - \"fields_deactivating_stake\") / 1000000000 FROM \"validators_info\" WHERE (\"host\" =~ /^$node11$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fields_activated_stake" ], "type": "field" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node11$/" }
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 1, "x": 20, "y": 20 },
   "targets": [
    {
     "measurement": "validators_info",
     "select": [
      [
       { "params": [ "fields_voting_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "autssvetlana-testnet" }
     ]
    }
   ]
  }
 ]
}